services:
  web:
    image: nginx:latest
    container_name: sam
    ports:
      - "8080:80"
    volumes:
      - ./content/examples:/content/examples:ro      
      - ./sam/web:/usr/share/nginx/html:rw
      - ./sam/package.json:/usr/share/nginx/html/package.json:ro
      - ./sam/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    command: /bin/sh -c "ln -sfn /content /usr/share/nginx/html/content && nginx -g 'daemon off;'"
    restart: unless-stopped
    depends_on:
      - puppeteer    
  
  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml
    restart: unless-stopped
  
  puppeteer:
    build: ./sam/puppeteer
    container_name: puppeteer
    restart: unless-stopped
    volumes:
      - ./sam/puppeteer/main.js:/app/main.js:ro
      - ./sam/puppeteer/export:/app/export:ro